wip

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,2 +1,24 @@
 #!/usr/bin/env bash
 # bin/compile <build-dir> <cache-dir> <env-dir>
+
+### Configure environment
+
+set -o errexit    # always exit on error
+set -o pipefail   # don't ignore exit codes when piping output
+unset GIT_DIR     # Avoid GIT_DIR leak from previous build steps
+
+### Configure directories
+
+BUILD_DIR=${1:-}
+CACHE_DIR=${2:-}
+ENV_DIR=${3:-}
+
+BP_DIR=$(cd "$(dirname "${0:-}")"; cd ..; pwd)
+
+for d in $BUILD_DIR/public/storeraiser/* ; do
+  cd $d
+  ls .
+  chmod 744 ./scripts/build.sh
+  ./scripts/build.sh
+done
+
